language: ruby
rvm:
  - "1.7.0"
  - "1.8.0"
  - "1.9.0"
  - "2.0.0"
  - "2.1.0"
  - "2.2.0"
  - ruby-head
  - jruby-head

before_install:
  - gem update --system
  - gem --version

gemfile:
  - Gemfile

notifications:
  email: false
